add delete text
RockefellerArchiveCenter/rac_aspace pull request #12
Opened 2020-01-21 21:13 UTC by p-galligan

Adding the delete section to the Readme.

As with our other issue, we're not quite sure what else there is to this.

2020-01-21 22:13 UTC, helrond requested changes
This is a really useful distinction, I think (and one that I hadn't really thought about). I wonder if we can build this out with a bit more technical detail about what is required in each case? The first would require a DELETE request against an endpoint, while the second requires a POST with some JSON as a payload? I think that will help us see where the overlaps are.

2020-01-22 14:51 UTC, p-galligan commented
@helrond and @HaSistrunk added some more specific data and also added some text about deleting orphan containers, and idea I just had this morning.

2020-01-22 19:53 UTC, HaSistrunk approved these changes

2020-01-22 20:58 UTC, helrond approved these changes
I'm not convinced we need a `delete_orphans()` method (or that this library needs to cover delete requests to existing endpoints since I'm not sure what the gain is there) but I'd argue for leaving this as-is for now because it's a really comprehensive scoping of the problem which we can refine as we start to write code.

2020-01-22 21:35 UTC, HaSistrunk approved these changes

2020-01-23 19:26 UTC, merged