Issue 27
RockefellerArchiveCenter/rac_aspace pull request #68
Opened 2020-03-17 18:58 UTC by daremiyo

## Changes

- Adds autodocs
- Adds autodoc directives for data_helpers
- Sets up autodocs config to organize directives by source
- Sets up autodocs config to mock import from fuzzywuzzy

## Questions

- Is by source the desired arrangement for autodoc directives?
- Mocked import from fuzzwuzzy because the import blocked sphinx from generating the html site. Error said that sphinx could not find module for fuzzwuzzy. Is mock import the best strategy for this scenario? 

Fixes #27

2020-03-17 20:29 UTC, p-galligan commented on .docs/conf.py
> +extensions = [ 'sphinx.ext.autodoc', 'sphinx.ext.coverage', 'sphinx.ext.napoleon'
You should remove the space after `[` here for linting.

2020-03-17 20:29 UTC, p-galligan commented on .docs/conf.py
> +]
Fix indenting here to line up with opening bracket to passing linting.

2020-03-17 20:30 UTC, p-galligan requested changes
I think a couple of changes will get this to pass linting.

2020-03-17 20:34 UTC, helrond requested changes
This is great @daremiyo, just a few small changes to align with past practice around corporate authorship!

2020-03-17 20:34 UTC, helrond commented on .docs/conf.py
> +copyright = '2020, Hillel Arnold, Amy Berish, Patrick Galligan, Bonnie Gordon, Katie Martin, Hannah Sistrunk, Darren Young'
```suggestion
copyright = '2020, Rockefeller Archive Center'
```

2020-03-17 20:34 UTC, helrond commented on .docs/conf.py
> +author = 'Hillel Arnold, Amy Berish, Patrick Galligan, Bonnie Gordon, Katie Martin, Hannah Sistrunk, Darren Young'
```suggestion
author = 'Rockefeller Archive Center staff'
```

2020-03-18 12:36 UTC, p-galligan commented on .docs/conf.py
> +             ]
```suggestion
              ]
```

2020-03-18 13:40 UTC, p-galligan commented
Looks good to me now! Looks like it's just failing on 3.4 and 3.5 which could be fixed by changing some info in the requirements file. You'd have to downgrade pre-commit to an earlier version.

2020-03-18 14:03 UTC, HaSistrunk commented
I'm wondering if it's ok to leave the pre-commit version as is in the PR since PR #66 will fix this issue?

2020-03-18 14:04 UTC, p-galligan commented
> I'm wondering if it's ok to leave the pre-commit version as is in the PR since PR #66 will fix this issue?

I personally think that's fine. It's passing most tests now.

2020-03-18 14:11 UTC, helrond commented
I think there's an order of operations thing here - we're going to have a lot of merge conflicts in the requirements file, so I think we may need to talk about what gets merged first, and how important it is for us to merge only working code. I think there are two paths:
- Merge #66 first, and then update each of the PRs to use those multiple requirements files. Downside is a lot of fixing PRs, upside is that we don't merge non-working code.
- Merge everything BUT #66 first, regardless of whether it's passing CI, and then merge #66, which should allow everything to pass. Downside is there might be additional bugs exposed which would have to be fixed, upside is fewer PR fixes.

Now that I'm writing this out, I think I'd prefer the first option - it keeps problems isolated and diagnosable.

2020-03-18 14:24 UTC, p-galligan approved these changes

2020-03-18 14:36 UTC, helrond approved these changes

2020-03-25 14:54 UTC, merged