Issue 90
RockefellerArchiveCenter/rac_aspace pull request #94
Opened 2020-04-28 18:51 UTC by a-berish

## Changes
- remove napoleon extension from docs config

- update readme to remove reference to napoleon

- update docs strings to use Sphinx

- change args from JSONModelObject to dict (where applicable) 

## Questions
None

## Blockers
None

2020-04-28 19:41 UTC, helrond requested changes
Wow this looks nice! I just added one typo I noticed.

Otherwise, two things:
1. We're missing a docstring for `rac_aspace.serializers.BaseSerializer.read_data()`. That's probably my bad, but would you all be able to add that?
2. in the documentation for the CSVSerializer and TSVSerializer I'm seeing the properties showing up.
<img width="876" alt="Screen Shot 2020-04-28 at 2 33 39 PM" src="https://user-images.githubusercontent.com/607621/80530281-61dc9a80-895e-11ea-875a-77220bbef22c.png">
Is there anything we can do about that?

2020-04-28 19:41 UTC, helrond commented on rac_aspace/data_helpers.py
>      Starts with an archival object, and iterates up through it"s ancestors
```suggestion
    Starts with an archival object, and iterates up through its ancestors
```

2020-05-01 16:11 UTC, helrond approved these changes

2020-05-01 16:12 UTC, helrond commented
@a-berish just need to make sure linting passes.

2020-05-01 16:15 UTC, p-galligan approved these changes
Approved based on linting fix.

2020-05-01 16:29 UTC, merged